# Creating Dataframes

In [1]:
import pandas as pd 
import numpy as np 

In [2]:
# creating dataframes using numpy arrays

data  = np.random.random(size = (5, 3))
print(data)

[[0.53449242 0.15554518 0.72794533]
 [0.26772658 0.1314119  0.3405113 ]
 [0.47876654 0.4255213  0.82061199]
 [0.1061948  0.09504576 0.42518628]
 [0.26255167 0.41430297 0.06199731]]


In [3]:
df = pd.DataFrame(data, columns=["A", "B", "C"])
df.head()

A         B         C
0  0.534492  0.155545  0.727945
1  0.267727  0.131412  0.340511
2  0.478767  0.425521  0.820612
3  0.106195  0.095046  0.425186
4  0.262552  0.414303  0.061997

In [7]:
# create dataframe from structured numpy array

dtype = [("A", np.int), ("B", (np.str, 20))]

data = np.array([(1, "Sam"), (2, "Alex"), (3, "John")], dtype = dtype)

df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [4]:
# creating dataframes by using dictionaries

df = pd.DataFrame(data = {"A": [1, 2, 3], "B": ["Sam", "Alex", "John"]})
df

A     B
0  1   Sam
1  2  Alex
2  3  John

In [8]:
# less common way of creating dataframe using dictionary

data = [{"A": 1, "B": "Sam"}, {"A": 2, "B": "Alex"}, {"A": 3, "B": "John"}]

df = pd.DataFrame(data)
df

A     B
0  1   Sam
1  2  Alex
2  3  John